language: cpp
matrix:
  include:
    - os: linux
      sudo: required
      compiler: gcc
      env:
      - UID_FILENAME=faf-uid.exe
      - UID_PLATFORM='win32'
      - MXE_DIR=/usr/lib/mxe
      - MXE_TARGET=i686-w64-mingw32.static
      install:
      - echo "deb http://pkg.mxe.cc/repos/apt/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mxeapt.list
      - sudo apt-key adv --keyserver x-hkp://keys.gnupg.net --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
      - sudo apt-get update
      - sudo apt-get --yes install
        python3
        mxe-$MXE_TARGET-jsoncpp
        mxe-$MXE_TARGET-cryptopp
        mxe-$MXE_TARGET-icu4c
      script:
      - mkdir build && cd build
      - $MXE_DIR/usr/bin/$MXE_TARGET-cmake
        -DCMAKE_BUILD_TYPE=Release
        -DCRYPTOPP_LIBRARIES=/usr/lib/mxe/usr/$MXE_TARGET/lib/libcryptopp.a
        -DCRYPTOPP_INCLUDE_DIRS=/usr/lib/mxe/usr/$MXE_TARGET/include
        -DUID_SKIP_LEGACY=On
        -DUID_PUBKEY_BYTES=`../encode_openssl_modulus.py $modulus`
        ..
      - make -j8
      - cd ..
    - os: linux
      sudo: false
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-6
            - cmake
            - cmake-data
            - python3
      env:
      - UID_FILENAME=faf-uid
      - UID_PLATFORM='linux'
      - JSONCPP_VERSION=1.7.7
      - CRYPTOPP_VERSION=5_6_5
      install:
      - wget https://github.com/open-source-parsers/jsoncpp/archive/$JSONCPP_VERSION.tar.gz -O jsoncpp.tar.gz
      - tar xfz jsoncpp.tar.gz
      - mkdir jsoncpp-build
      - cd jsoncpp-build
      - cmake
        -DCMAKE_BUILD_TYPE=MinSizeRel
        -DCMAKE_CXX_COMPILER=g++-6
        -DJSONCPP_WITH_POST_BUILD_UNITTEST=OFF
        -DBUILD_STATIC_LIBS=ON
        -DBUILD_SHARED_LIBS=OFF
        ../jsoncpp-$JSONCPP_VERSION
      - make -j8
      - cd ..
      - wget https://github.com/weidai11/cryptopp/archive/CRYPTOPP_$CRYPTOPP_VERSION.zip -O cryptopp.zip
      - unzip ./cryptopp.zip
      - mv cryptopp-CRYPTOPP_$CRYPTOPP_VERSION cryptopp
      - cd cryptopp
      - make -j8 -f GNUmakefile CXX=g++-6 CXXFLAGS='-DCRYPTOPP_NO_BACKWARDS_COMPATIBILITY_562 -DNDEBUG -O3' libcryptopp.a
      - cd ..
      script:
      - mkdir build && cd build
      - cmake
        -DCMAKE_CXX_COMPILER=g++-6
        -DJSONCPP_LIBRARIES=$TRAVIS_BUILD_DIR/jsoncpp-build/src/lib_json/libjsoncpp.a
        -DJSONCPP_INCLUDE_DIRS=$TRAVIS_BUILD_DIR/jsoncpp-$JSONCPP_VERSION/include
        -DCRYPTOPP_LIBRARIES=$TRAVIS_BUILD_DIR/cryptopp/libcryptopp.a
        -DCRYPTOPP_INCLUDE_DIRS=$TRAVIS_BUILD_DIR
        -DCMAKE_CXX_FLAGS="-DCRYPTOPP_NO_BACKWARDS_COMPATIBILITY_562"
        -DCMAKE_BUILD_TYPE=MinSizeRel
        -DUID_PUBKEY_BYTES=`../encode_openssl_modulus.py $modulus`
        ..
      - make -j8
      - cd ..

script:
  - echo "Nothing."

before_deploy:
  - export RELEASE_PKG_FILE=./build/$UID_FILENAME

deploy:
  provider: releases
  api_key:
    secure: dXe34Fx7IZJHnCDr1POgDI2Klm+R+PSh/r7oPFZwAN3A2Rgwmj5zLD3EeFIOUNqsB2ROtqzInhRAuHvPsEauPqSk2cgoWNQA3BpemgiXvaVGsMXsEFl05bURcC1ViWsI0DNGJSyLGlWphXV1LmqBXMcbUwv2dv4hVBU3ZR3FYVtd2dYgq1Ee3FRy1ZjTbTF495F4kEtYbQYYaq8jpW+cn5LTATu0enRZ/TC4b9AmgoTMYcjarw8DOZW59jogHFJYoTAdjklhyzpDdhuFS7ASkedX/ZsGYKbl9cllHBPo8hjxLGtLWbclHN2qob6n7QT4oa6k7pEnw2/TCjglKB4cuG0vhmtexNKFD4UMLdqxIqaSj2tsIyopXSf/qjwq9PMdxlY3Po+v1I/BdcT6U4c14wDpUE+ouyO5yhTF3zDJidJNnu8B0BgbVENuvax06Mw6/ho7Tt8YUANQ6h0RrrU71TBmG430S2hdOct2Fu9HNs+9zPGyX97lGPEVkYflaAtN83//oWijdxvh52UsRYdyu9n6rTdOr6CCeNY2TH7qe0kVTGZECCSW4fZ+/gNkFk5Xg2kx4R+jm0PsYEaFLVzZsWR0RnbJVFYZiBiWPABKAA3DtesRdL0DPI6VkvJx1bKJ9Ltwtu7fH6CVAQrHaL0gI7Bsk5t6ZwMONMBO8uAgOuA=
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    tags: true
