language: cpp
matrix:
  include:
    - os: linux
      sudo: required
      compiler: gcc
      env:
      - UID_FILENAME=uid.exe
      - UID_PLATFORM='win32'
      - MXE_DIR=/usr/lib/mxe
      - MXE_TARGET=i686-w64-mingw32.static
      install:
      - echo "deb http://pkg.mxe.cc/repos/apt/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mxeapt.list
      - sudo apt-key adv --keyserver x-hkp://keys.gnupg.net --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
      - sudo apt-get update
      - sudo apt-get --yes install
        python3
        mxe-$MXE_TARGET-jsoncpp
        mxe-$MXE_TARGET-cryptopp
        mxe-$MXE_TARGET-icu4c
      script:
      - mkdir build && cd build
      - $MXE_DIR/usr/bin/$MXE_TARGET-cmake
        -DCMAKE_BUILD_TYPE=Release
        -DCRYPTOPP_LIBRARIES=/usr/lib/mxe/usr/$MXE_TARGET/lib/libcryptopp.a
        -DCRYPTOPP_INCLUDE_DIRS=/usr/lib/mxe/usr/$MXE_TARGET/include
        -DUID_SKIP_LEGACY=On
        -DUID_PUBKEY_BYTES=`../int_to_bytes.py $n`
        ..
      - make -j8
      - cd ..
    - os: linux
      sudo: false
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-6
            - cmake
            - cmake-data
            - python3
      env:
      - UID_FILENAME=uid
      - UID_PLATFORM='linux'
      install:
      - wget https://github.com/open-source-parsers/jsoncpp/archive/1.7.2.tar.gz -O jsoncpp.tar.gz
      - tar xfz jsoncpp.tar.gz
      - mkdir jsoncpp-build
      - cd jsoncpp-build
      - cmake
        -DCMAKE_BUILD_TYPE=MinSizeRel
        -DCMAKE_CXX_COMPILER=g++-6
        -DJSONCPP_WITH_POST_BUILD_UNITTEST=OFF
        -DBUILD_STATIC_LIBS=ON
        -DBUILD_SHARED_LIBS=OFF
        ../jsoncpp-1.7.2
      - make -j8
      - cd ..
      - wget https://www.cryptopp.com/cryptopp563.zip
      - mkdir cryptopp
      - cd cryptopp
      - unzip ../cryptopp563.zip
      - make -j8 -f GNUmakefile CXX=g++-6 CXXFLAGS='-DNDEBUG -O3' libcryptopp.a
      - cd ..
      script:
      - mkdir build && cd build
      - cmake
        -DCMAKE_CXX_COMPILER=g++-6
        -DJSONCPP_LIBRARIES=$TRAVIS_BUILD_DIR/jsoncpp-build/src/lib_json/libjsoncpp.a
        -DJSONCPP_INCLUDE_DIRS=$TRAVIS_BUILD_DIR/jsoncpp-1.7.2/include
        -DCRYPTOPP_LIBRARIES=$TRAVIS_BUILD_DIR/cryptopp/libcryptopp.a
        -DCRYPTOPP_INCLUDE_DIRS=$TRAVIS_BUILD_DIR
        -DCMAKE_BUILD_TYPE=MinSizeRel
        -DUID_PUBKEY_BYTES=`../int_to_bytes.py $n`
        ..
      - make -j8
      - cd ..

env:
  global:
  - secure: gZJEU+r0BJYH3GxoQAUWUUAse6VlOT28pTnT07ft2vrutTr0Q9383OpNlxkCZ34BBXr2hDlwAYkO1oy4lLQoyjAe59KPSuTmbGZloI/4DojEuwxf5rDHeVK8YkA/cmP6UW2BHpBOCYor4l0lz9XihFPuiriiRiy0BkRK3mwMTBO18SmjbxXw49si1/6oVJupuT4UYUHQbu6MNAYyIPcPQKMPEYOdV5AkIb9cKM+QMpExC+Sby/f/4m68J9MygcM+YMbb+PuWvuUot4FzTrWjswLp1slbI8YdN7BoC4hyPlW9Tuquq40WSTeTf2S/BS1qkfvFHpddF5OEcGvfkameg7mo1J1ZZWv8wlrM513FWM+t4QKNkXadqFetbznm94bNrnVvU6R7Z7Utf4+zl4TW9z5lb8KyO+nu/qFlWf2qORyyVTmxXeLXaK9ZDtr5QFgPfk4tKcVlnD2ECtYcm35TtEJF5dkOpETYG30W+6fd1glw3oQKj5gWJrPCC50mss3C/zsWN2tHTbeGSgix3hNrDsJuMcELkDdJIkAAhn1WnVyAfdt5hSX9A0S4W131G5t6I00lZs1e+ZAzOr5+LvotLtg1W48xIQtrbv2GEBkZEyV/bsOoLSyTLFelN6ehiq/eALQEhHodxx8P3tDgi5jG4SKPcqdi6fSwnGfPvpbZbMI=
  - secure: V23UleSDM9vYuhFY68JY+VPBNF1DxFh0y7LB9U0RNql05dJv02QjU+W/eteAJ+VkhqrIq1XDaIMYp3/eon+tT+iT9xtIdaj0DreaWu0paCfaVITOHBYARDmTwwo7i/NvUdZbAyjKEc7dpxBkZwHZCpu9dIUOqXGg/cKmDQdKeNsNITJOsudueeeMp1P5eWj1om/PH/8PhwteSvJwTPXOKIhAj2IVL4EkiFkMEA9cIF4u/y6IkugnJsDCBqnr5SsioM6XXEbe6i0l9/ngSs2y20peFNnSITrzw/2xKlolLHfmFO/0ubmHAxBXC5W9cP4Fk2FGdY10rFh6MoCjgyjUYm0xfP+s6Nhx4yjkG9kNm1CXkl4TZyNdQu2qoVsrLJhZ4Y/yPiusmuWZWdlxu2l10UPrt35VtZtD5VosNZ/otMHErv/TLwEzqw3rpPW48Cyx/HeVg4PMTKad0amIsGpykW3ghLh7N0cvBqh3b0Yk7k2UsLf/6I7f1OcleUejDNpkoC/fjMSB/jQ6B3LfFMrzMur5kzzoqla6TLp/OWs9eoGXeu9Iw58XmvvMkcoNCQgntT2tm9t7XaOpURHDpKGwl5G59DbpWXFTq9qF5gjhT/9EuH18OtEzhkBA+jivR2P7lj9NeQMDqkww4wmgf740+8dcq82thqgY+Cckf/X2XZM=

script:
  - echo "Nothing."

before_deploy:
  - export RELEASE_PKG_FILE=./build/$UID_FILENAME
  
deploy:
  provider: releases
  api_key:
    secure: WhOx05Op3wMQaCxCzjMfLX75z3xyElczH6lAFKltpWyRoacYgfFW0Z73he1f0AUCcXbuFB/oxlpIPwQNxv5xisJBoDDgcz0FWxe0Dig8KooVcvp5OAhL44qWpIH5fkFRSHZ+zNdR3mmmGVd17dKmRxvMdTqUxp4dYtZfRTMKDzZt/2+IqAHizUmBlZsLzyjeLyMQcKzNlpuh71hGo73LiaU6pCKdp46GSWOkJpMoSTI0jlym6viVkEjskjU5umY+TPZ39ud3BxjuUtDpMo7ph3j+2rK080m5Vj5n33aHoOKUW3fyC1vOEz1pyVHc2jXd9A8UhYg7RXK2RPbr9vet9rmM2Y/29UV6RGy3BfpR9rc+Phrj9hyloJ6x2m3Sy7TZZw0/d2zkj/+gkY30bHklhxHipDBT5K3qdZwWEVCdSaO9ucI4WAXKvYXXIxv+dcFjW0HL3vrxZO5eD+pPHw2Q3n2bzJ8pjBuxyHJ3WW/f73tlargXXS6VsN8YPpp/BmBzEAGTHGv7bvB6CTrdgZiJ8EDsWaILXObzYwUKa/fMZ/KlX+JQmSlXdJAUoRdegBq+9YC7teJbZbzksEQtvHbz46gmdO+qV9r+D3evPobUUHlSp6Hy0egp+d1OHPeAOd42yjmuJEIcvGgPGSAab3nsxvjZPYmgiQ8dvw4iYlSIHOY=
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    tags: true
