version: win32-{build}
skip_non_tags: true
environment:

  e:
    secure: y0WQqkPEC4eaCc3fr/b4HA==
  n:
    secure: /uv7YxWVLhhE3bs4nPQrHYp3G6EaNd8ZNOkPI+0aZPATvpBfjKupJQTCZY82savG9yi9VGBSxpVNKiesYzDczxUUFhk4neDZhTBKVR8kREw=
install:
- ps: >-
    C:\Miniconda\Scripts\pip install --quiet -r requirements.txt

    C:\Miniconda\Scripts\pip install --quiet -r requirements_win.txt

    C:\Miniconda\Scripts\conda install --quiet -y pyqt pywin32
build_script:
- ps: >-
    (Get-Content .\uid\__init__.py) -replace '13731707816857396218511477189051880183926672022487649441793167544537', "$env:n" | Set-Content .\uid\__init__.py

    (Get-Content .\uid\__init__.py) -replace '65537', "$env:e" | Set-Content .\uid\__init__.py

    C:\Miniconda\Scripts\nuitka --recurse-to=rsa --recurse-not-to=pyasn1.type --recurse-not-to=Crypto --recurse-not-to=pyasn1.codec.der --recurse-not-to=win32com.client --recurse-to=wmi --module uid --output-dir=build --remove-output

    (Get-Content .\uid\__init__.py) -replace "$env:n", '13731707816857396218511477189051880183926672022487649441793167544537' | Set-Content .\uid\__init__.py

    (Get-Content .\uid\__init__.py) -replace "$env:e", '65537' | Set-Content .\uid\__init__.py
test_script:
- cmd: C:\Miniconda\Scripts\py.test -vv --full-trace
artifacts:
- path: ./build/uid.pyd
  name: uid_windows_binary
deploy:
- provider: GitHub
  auth_token:
    secure: OnBDCRKgFEo0gcsSFEdPd7oPcZQMIMBb9lzkNRcYMK3WAHaR34WnBKwLBCsDBSgj
  artifact: uid_windows_binary
