environment:

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.11"
      PYTHON_ARCH: "32"
      n: 13731707816857396218511477189051880183926672022487649441793167544537
      e: 65537

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %QTIMPL%"

install:
  - "C:\\Python27\\python -u appveyor\\install_qt.py"
  - ps: (new-object net.webclient).DownloadFile('http://nuitka.net/releases/Nuitka-5.1.211.win32.py27.msi', 'nuitka.msi')
  - ps: msiexec /i nuitka.msi /quiet /qn /norestart /log install.log
  - "%PYTHON%\\Scripts\\pip.exe install -r requirements.txt

test_script:
  
after_test:
  - "powershell -ExecutionPolicy ByPass -File .\build.ps1"

artifacts:
  - path: 'build\uid.pyd'

build: off
