version: appveyor-win32-{build}
environment:
  n:
    secure: zauy6DWrhZv/OgNsvdiIkPaT02Tc2ZAhXw5OE8FWS+4+yHt+P4KbZCaGbRZo9dZ+qTt9jcw2igDuRYiH6GPE0aft7y3/lQ93VnHAtfR3E+E=
  e:
    secure: MUEbYxEMAmV/rJZNG/M8TA==
install:
- ps: >-
    C:\Miniconda\Scripts\pip install --quiet -r requirements.txt

    C:\Miniconda\Scripts\pip install --quiet -r requirements_win.txt

    C:\Miniconda\Scripts\conda install --quiet -y pyqt pywin32
build_script:
- ps: (Get-Content .\uid\__init__.py) -replace '13731707816857396218511477189051880183926672022487649441793167544537', "$env:n" | Set-Content .\uid\__init__.py
- ps: (Get-Content .\uid\__init__.py) -replace '65537', "$env:e" | Set-Content .\uid\__init__.py
- ps: C:\Miniconda\Scripts\nuitka --recurse-to=rsa --recurse-not-to=pyasn1.type --recurse-not-to=Crypto --recurse-not-to=pyasn1.codec.der --recurse-not-to=win32com.client --recurse-to=wmi --module uid --output-dir=build --remove-output
- cmd: dir /s
- ps: (Get-Content .\uid\__init__.py) -replace "$env:n", '13731707816857396218511477189051880183926672022487649441793167544537' | Set-Content .\uid\__init__.py
- ps: (Get-Content .\uid\__init__.py) -replace "$env:e", '65537' | Set-Content .\uid\__init__.py
test_script:
- cmd: C:\Miniconda\Scripts\py.test -vv --full-trace
artifacts:
- path: '**\*.pyd'
  name: uid_win32_module
deploy:
- provider: GitHub
  auth_token:
    secure: sZ4+uH1Nno04dbBezqqF+D3vkBdiuAP6zXthszDBrozXf8eUJQtVEQGdwB4Ghv4u
  artifact: uid_win32_module
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    appveyor_repo_tag: true        # deploy on tag push only
